### ISSUE TITLE
Pas de "create database"+"use" dans le MPD

### ISSUE THREAD

**Issue by jframiara** [c-bringer/PPE-FREDI#13]
Le script SQL ne contient pas la création de la base, il faut la faire à la main à chaque installation.

**Comment by GuillaumeEscaffre** [comment]
Bonjour, la création de la base est maintenant dans le script SQL, il faut juste penser à enlever la vérification des clefs étrangères.

**Comment by jframiara** [comment]
OK, c'est bon.
