### ISSUE TITLE
Impossible de s'inscrire

### ISSUE THREAD

**Issue by jframiara** [c-bringer/PPE-FREDI#19]
Impossible de s'inscrire. Le mot de passe n'est pas reconnu même si on en demande un nouveau.
Le compte "adherent" fourni ne marche pas non plus.

**Comment by GuillaumeEscaffre** [comment]
Le problème était connu, je viens de régler le problème. La base est dorénavant normalement fonctionnelle.

**Comment by jframiara** [comment]
OK, c'est bon.
