### ISSUE TITLE
Erreur lors de la création du bordereau

### ISSUE THREAD

**Issue by jframiara** [c-bringer/PPE-FREDI#22]
Lors de la création du bordereau, on obtient une erreur de syntaxe :
Parse error: syntax error, unexpected '<<' (T_SL), expecting end of file in C:\xampp\htdocs\projets\PPE4\FREDI_g1\PPE-FREDI-master\bordereau.php on line 65
![image04](https://user-images.githubusercontent.com/23612833/77931126-0dd18e00-72ac-11ea-8861-34f0d11a6f1f.jpg)

De plus, il y a un merge conflict non résolu dans le fichier bordereau.php.
![image05](https://user-images.githubusercontent.com/23612833/77931285-47a29480-72ac-11ea-980a-41e3c82c9bd9.jpg)

**Comment by c-bringer** [comment]
Le conflit de git et l'erreur de syntaxe est maintenant corrigé.

**Comment by jframiara** [comment]
OK c'est bon.
