### ISSUE TITLE
Code : Modifier / Supprimer une ligne de frais

### ISSUE THREAD

**Issue by cpuel** [c-bringer/PPE-FREDI#8]
La modification / suppression d'une ligne de frais se fait sans demande de confirmation.
De plus, il est possible de modifiée une ligne de frais déjà validée.

**Comment by c-bringer** [comment]
Les messages de confirmation sont visibles lorsqu'on clique sur "supprimer" ou "modifier".
Cette dernière vérification n'est pas encore faite
